### ISSUE TITLE
Filter product by Assurance partner

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/sib-discovery-components#16]

**Comment by mariocarabotta** [comment]
working as expected 👍
again, only issue is visual styling as per #6

**Comment by kirstenalarsen** [comment]
I don't think this is working for Products.
We have a test case of Pukawidgee for AHMC Assurance Partner
It works on Producer page

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/d4fd0375-8003-4ccd-bd22-99aab8e5b2a0)

Pukawidgee has products 
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/4451f989-d6e2-4bd1-99e8-7bb131df3207)

But when I filter Products by Assurance Partner nothing comes up 

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/b2591fb7-67e5-42c9-b5cb-4cbcd1773214)

**Comment by JbPasquier** [comment]
Sent back to Benoît. We're investigating.

**Comment by JbPasquier** [comment]
Fixed!

![image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/5b9b2154-c90a-4496-ae31-387f331cfe6e)

**Comment by kirstenalarsen** [comment]
yep good :)
