### ISSUE TITLE
View producer basic details

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/sib-discovery-components#17]
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/9dfb2e52-8c29-4dab-acde-e2a26e4dad0c)

**Comment by kirstenalarsen** [comment]
When I click into a Producer that has a short profile i.e. not much information, it is scrolling me straight to the bottom so I'm only looking at the footer

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/571e1290-eb1c-40d9-9dec-7f9c60b6af94)

and I have to scroll up to see the actual info

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/3ad025d6-d112-4626-a8af-f38777789995)

This is in the wordpress embed (regenerative.org.au/test) not the SiB staging site so it might be wordpress related @mkllnk

**Comment by mkllnk** [comment]
@JbPasquier, can you shed some light on this? How does it scroll? Which anchor does it use?

**Comment by JbPasquier** [comment]
I found an issue in the SIB Router, I fixed it, Benoît will merge it as soon as he'll be able to review it.

**Comment by JbPasquier** [comment]
It has been merged, @mkllnk can you update your WP's head to these lines:

```
<script type="module" src="https://cdn.skypack.dev/@startinblox/core@0.19"></script>
<script type="module" src="https://cdn.skypack.dev/@startinblox/router@0.12"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@startinblox/component-ofn-rpp"></script>
```

(`router@0.12` instead of `router@0.11`)

**Comment by mkllnk** [comment]
Yay, it works!

**Comment by mariocarabotta** [comment]
1. location format under the name is not as expected.
it should be {City} - {State}        {First Nations Country}

Note: First Nations Country is optional

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/75126e10-7759-4ea5-b304-c10c5a725cc4)

2. if possible, could you please move the tags above the title? We're noticing people adding loads of categories and it breaks the layout. Apologies for this, I was not expecting it.

**current**
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/ec075ff5-d061-475b-b2b0-83069989b1e8)

**expected (if possible)**
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/51d6bcd4-0404-45f5-aa0b-c29a96670580)

3. Learn more about us needs underline style

4. Align title and line divider to rest of elements. See below for gaps
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/dbb442b3-32ff-49ab-98ee-3945c67d2f32)

**Comment by JbPasquier** [comment]
Done.

![image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/9fde3b26-1960-42d9-ad0b-c6183cc1cfb6)
