### ISSUE TITLE
Filter Producer by First Nations led

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/sib-discovery-components#18]
First Nations led filter is currently not working correctly

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/0aa677b9-24ed-4218-b05f-66036d378e8b)

Part of the problem might be data @mkllnk @mariocarabotta - can we confirm that the API is bringing the correct data? The results displayed on the page are showing some Producers as FNL that shouldn't be i.e. Pukawidgee, Bundarra and Murrnong (despite them all being named with Aboriginal words!!) I'm not sure the correct spot to look in the airtable, but when I'm looking I don't see them as having FNL set, so not sure why that flag is appearing on the profiles

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/96a1b853-279b-445e-8c15-09490cd4fc33)

**Comment by mkllnk** [comment]
@JbPasquier acknowledged already that it's a framework issue on SiB side. The current version is feeding from the wrong field in the absence of being able to deal with the right field. Oh wait, just saw that one comment was edited:

> I still have a framework issue with the first nation led filter on products list. A fix will come as soon as possible. - Edit: Fixed.

@JbPasquier, maybe you missed an earlier comment on Slack:

> One thing we noticed is that the First Nations Led filter isn't right. There was no test data but we added that flag to an enterprise now: https://api.regenerative.org.au/webhook/regen/producer?id=recSrhBnWnzkFRS3y
There you can see the ofn:First_Nations_led field which is only present when set and then it's simply true (boolean).

I think that you are looking at `ofn:First_Nations_country` but you need to look at `ofn:First_Nations_led`.

**Comment by JbPasquier** [comment]
Oooh right, I was using the wrong field so. Fixed.

![image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/3cd5fae3-1abd-4cd0-bf0d-5dd83edae8a5)

Can you add a produce to this producer to ensure that the filter on Products List works properly too?

**Comment by mkllnk** [comment]
@kirstenalarsen We can't add products to that enterprise but could we add that flag to another with products?

**Comment by JbPasquier** [comment]
Should I keep the First Nation Country when First Nations Led is false?

Like there for Pukawidgee for instance:

![image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/289c1369-ef32-4b8c-a126-4a22e053b902)

**Comment by mkllnk** [comment]
> Should I keep the First Nation Country when First Nation Led is false?

Yes! In Australia, we all live on First Nation's Country but only very few organisations are led by Indigenous people. We want to acknowledge the traditional owners regardless of being indigenous to this land or not.

**Comment by kirstenalarsen** [comment]
I just created a test product for Laguna. we can clean it up later, will be
working with Producers to try and get a few products in each before launch

piong @Amida Cumming ***@***.***>

**Comment by mariocarabotta** [comment]
working as expected, product filter as well (see The Regenerative Farm DR Example).

Moving to done, good job!
