### ISSUE TITLE
Producers: 'Supporting Evidence' Filter (remove Certifications label)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/sib-discovery-components#21]
Consolidated list of Supporting Evidence classifications: https://n8n.openfoodnetwork.org.uk/webhook/regen/supporting_evidence_classifications

**Comment by kirstenalarsen** [comment]
excellent, a big step forward! 


![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/f778d018-2370-49cd-b728-a1c0a34e41d3)

[Y] The title of this needs to be 'Supporting Evidence' not 'Ecological Outcomes'
[] Needs to be multi-select as per openfoodfoundation/openfoodnetwork#20 
[] The Certifications button needs to select all Producers that have a Certification (same function as mentioned in [#12239](https://github.com/openfoodfoundation/sib-discovery-components/issues/69) could be an API thing, @mkllnk )

Currently only giving me the one that is certified biodynamic 
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/c74eb38a-2a92-4450-82ff-a6d31bd490ca)

[Y] Ordering - please make 'Other' appear at the bottom (same for on the Evidence filter)

**Comment by JbPasquier** [comment]
> The Certifications button needs to select all Producers that have a Certification (same function as mentioned in https://github.com/openfoodfoundation/sib-discovery-components/issues/69 could be an API thing, @mkllnk )

Exact, doing it in the API datas is the only way to handle that. I can't mix-match things like that.

**Comment by JbPasquier** [comment]
> Ordering - please make 'Other' appear at the bottom (same for on the Evidence filter)

To reach this, we should avoid ordering on client-side and have it at the end of the list on the API.

**Comment by JbPasquier** [comment]
> The title of this needs to be 'Supporting Evidence' not 'Ecological Outcomes'

Done.

**Comment by mkllnk** [comment]
> Ordering - please make 'Other' appear at the bottom (same for on the Evidence filter)

Done in the API. Should be visible tomorrow.

**Comment by kirstenalarsen** [comment]
We have discussed and the problem is in the data. 
- There are two 'tags' one is Certifications and the other is Certification
- 'Certifications' can be selected from a drop-down list when people are adding Supporting Evidence
- 'Certification' is automatically added when a user adds assurance type Certification
- Currently the 'Certifications' filter on the Producer list, looks at Assurance type 'Certification' - it doesn't look at anything else added under Supporting Evidence
- The 'Supporting Evidence' filter, has a category for Certifications that ONLY looks at Supporting Evidence that has been tagged 'Certifications'
 
We are not clear what we WANT this to do . . 

Kirsten feeling would be that:
- When I select Certifications under Supporting Evidence, I see filtered list of all Producers that have a Certification 
- The alternative would be to actually just remove this from SE filter 
- Certifications filter - I would still like it to have an 'All Certified' option, that enables the user to see all Producers that have a Certification (i.e. like an ALL option on a multi-select)

**Comment by kirstenalarsen** [comment]
OK, we've made some decisions. We are going to remove 'Certifications' as a tag on Supporting Evidence as it's confusing and duplicative. To action this:

@mariocarabotta can you please remove in Airtable / Miniextensions
@mkllnk can you please remove from API if needed
@JbPasquier can you remove the Certifications label from the Supporting Evidence dropdown, if it doesn't disappear automatically after the above!

Thanks!

**Comment by mariocarabotta** [comment]
removed from airtable

**Comment by mkllnk** [comment]
Removing from Airtable was enough, there was not special data held in n8n. Ready for testing.

**Comment by kirstenalarsen** [comment]
yep
