### ISSUE TITLE
Embed SiB Directory Components in Canadian WP site

### ISSUE THREAD

**Issue by David-OFN-CA** [openfoodfoundation/sib-discovery-components#59]
**Description**

To begin configuration and testing of Canadian Waterloo Food Commons(ref [#12411](https://github.com/openfoodfoundation/openfoodnetwork/issues/12411)), we need to get  [Discover Regenerative](https://github.com/orgs/openfoodfoundation/projects/10) SiB web components embedded in the new Canadian wordpress site.

I think this may entail forking the components first, but would need @mkllnk or @rioug to confirm?

Once the SiB components are embedded in the Canadian wordpress site, Canadian team will begin testing to see what modifications (if any) are needed to the SiB components to support deployment of the Waterloo Food Commons (CA) [#12411]

Task list:

- [x] Set up Wordpress site (this is almost done, hosting has been set up - install of wordpress in process)
- [x] Embed SiB components in Canadian WP site

**Comment by David-OFN-CA** [comment]
@mkllnk, @rioug, @kirstenalarsen - just confirming that the Canadian WP site is setup in staging now - let us know what information and login details we need to share with you, in order to get the SiB components embed in Canadian WP site

**Comment by mkllnk** [comment]
You need to create a page and add an HTML block. In there you paste this code:
```html
<script type="module" src="https://cdn.skypack.dev/@startinblox/core@0.19"></script>
<script type="module" src="https://cdn.skypack.dev/@startinblox/router@0.12"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@startinblox/component-ofn-rpp"></script>

<solid-ofn-rpp
      producers-src="https://api.regenerative.org.au/webhook/regen/producer-bundle"
      products-src="https://api.regenerative.org.au/webhook/regen/product-bundle"
      range-product-categories="https://api.regenerative.org.au/webhook/regen/produce_categories"
      range-producer-assurances="https://api.regenerative.org.au/webhook/regen/assurance_partners"
      range-producer-supporting-evidence="https://api.regenerative.org.au/webhook/regen/supporting_evidence_classifications"
      range-producer-certifications="https://api.regenerative.org.au/webhook/regen/certifications"
      uniq="directory"
      route-prefix="directory"
    ></solid-ofn-rpp>
```

That should display the Australian data. By changing all the URLs from `api.regenerative.org.au` to n8n with your webhook URLs should then display your data.

**Comment by David-OFN-CA** [comment]
Thanks a lot @mkllnk - we'll move forward on this and keep you posted.

@RebeccaOFN - lets coordinate around following the steps Maikel describes above, and then we can loop @karlafalk in on configuring our n8n webhook URLs so that the components start displaying our data

**Comment by RebeccaOFN** [comment]
Thanks @mkllnk! I have the component in and working with Australian data. Moving on to next step in configuring for Canadian data.

**Comment by David-OFN-CA** [comment]
thanks everyone! I'm going to start a new issue now re changing all the URLs from api.regenerative.org.au to Canadian n8n webhook URLs, to display Canadian data.
