### ISSUE TITLE
Aquire Domain Name and Setup Staging Site

### ISSUE THREAD

**Issue by David-OFN-CA** [openfoodfoundation/sib-discovery-components#65]
@RebeccaOFN I belivie this is done? could you confirm and link to the new domain name / site below, and then we can close this issuec - cheers

**Comment by RebeccaOFN** [comment]
This is in progress, but experiencing a bit of a complication with our web host. Currently you can see progress on the staging site here: http://nrw.ocl.mybluehost.me/website_a64d4da6/staging/5285/component-test/

**Comment by RebeccaOFN** [comment]
Hi all, just confirming that this is done. You can see the staging site here: https://waterlooregionfood.ca/staging/5285/. The final domain (waterlooregionfood.ca) is active with a coming soon page.
