### ISSUE TITLE
Producer profile: supporting evidence summary (order and include Certifications from Assurance Type: Certification)

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/sib-discovery-components#8]
This is looking great. Links at top of page link down to filtered evidence is working great
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/17516f16-27b4-4c4d-82ce-582145ad3a03)

### Issues:
It seems like the filters are only showing when there is evidence and the order is maybe changing?
![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/38c45e31-9664-4373-a5c5-501fa6c3fc30)

In the mockup we had all the filters appearing regardless of results, and have a specific set order (as per below)
The thing that is most important to us is consistency of the order, which should be as per the mockup below (note we're not concerned about the indentation)

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/604be252-67e8-4820-a6e1-ffab54609a4a)

**Comment by JbPasquier** [comment]
> It seems like the filters are only showing when there is evidence and the order is maybe changing?

I do compile the list of possible filters based on what I have on the resource.

They're not ordered, first to come first to be shown. I can sort them.

Doing [...] Done.

![image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/d4fb5b7a-2745-4d1b-ac1f-865a15c2e5eb)

**Comment by kirstenalarsen** [comment]
Thank you! I also just noticed that the Source field is missing and the date format is different from designs / how we want i.e. dd/mm/yyyy

Design:


![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/bdfbba20-e21e-464b-ac7c-79842b80b860)


Current

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/37030dc6-c979-4622-8b46-f85498c61950)

**Comment by JbPasquier** [comment]
@mkllnk Can you point me which field is the source field?

~~About the date format, @mkllnk could it be handled on your side? If not, I can manage it on front-end but it may break if some date does not share the same format as others from the api.~~ I've updated the date format to force the usage of the browser's locale one, so it should always be properly displayed to the end-user, as long as the api does serve a yyyy-mm-dd format.

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/b8cfac3b-0c2b-4bf3-a467-d757e1ad1992)

**Comment by mkllnk** [comment]
@JbPasquier I needed to add the source to the API. The field is `ofn:Service_provider_name[0]` in example:
https://n8n.openfoodnetwork.org.uk/webhook/regen/assurance?id=recAmJx6YFmRH134j

Does that work?

**Comment by JbPasquier** [comment]
Does it needs to be an array? Should I expect receiving multiples sources?

Looking at the mock-up, it seems that it's a link to somewhere?

May I suggest you this format:

```json
{
  "@id": "https://n8n.openfoodnetwork.org.uk/webhook/regen/assurance?id=recAmJx6YFmRH134j",
  "ofn:sources": [
    {
      "ofn:label": "ANU Sustainable Farms",
      "ofn:uri": "https://www.anu..../"
    },
    ...
  ],
...
}
```

Or, if only one source can be present, the same way as you did for wholesale urls:

```json
{
  "@id": "https://n8n.openfoodnetwork.org.uk/webhook/regen/assurance?id=recAmJx6YFmRH134j",
  "ofn:source_label": "ANU Sustainable Farms",
  "ofn:source_uri": "https://www.anu..../",
...
}
```

A more specification-compliant approach would be:

```json
{
  "@id": "https://n8n.openfoodnetwork.org.uk/webhook/regen/assurance?id=recAmJx6YFmRH134j",
  "ofn:source": {
    "@id": "https://..."
    "ofn:label": "ANU Sustainable Farms",
    "ofn:uri": "https://www.anu..../"
  },
...
}
```

But I understand that you'd want to avoid adding one more endpoint to your n8n's api.

**Comment by mkllnk** [comment]
> Does it needs to be an array? Should I expect receiving multiples sources?

Only one source. The array comes from our data structure. Either you or I have to deal with it. :stuck_out_tongue: 

I didn't know about the URL. I'll add it like your option 2.

**Comment by mkllnk** [comment]
Here you got your example: https://n8n.openfoodnetwork.org.uk/webhook/regen/assurance?id=recAmJx6YFmRH134j
```
"ofn:service_provider_label":	"ANU Sustainable Farms",
"ofn:service_provider_uri":	"https://www.sustainablefarms.org.au/",
```

**Comment by JbPasquier** [comment]
Done!

While it's on n8n, it's still missing from the proxy https://api.regenerative.org.au/webhook/regen/assurance?id=recAmJx6YFmRH134j do you know how much time it usually takes to process the queue?

**Comment by mkllnk** [comment]
> do you know how much time it usually takes to process the queue?

No. At the moment I have it set to refresh every 8 hours but even if I reduce that to 1 minute it doesn't update straight away. We don't have a good cache invalidation strategy at the moment. I'll set it to 1 hour at some point for production, I think.

**Comment by kirstenalarsen** [comment]
sorry, really irritating detail - can you please add the colon after Source @JbPasquier, so it is "Source: " , currently missing


![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/06e63c8c-4cb6-4b2c-a0f2-6c8fea1ba095)

**Comment by JbPasquier** [comment]
Fixed

**Comment by kirstenalarsen** [comment]
@JbPasquier 
* Can we please have these ordered in this display in the same order as on the Filter. NB. The 'Certifications' option that is 'fed' from the Supporting Evidence label will be unused as we're removing that option BUT
* is it possible to have # Certifications appear here according to the logic of the Supported  Evidence on this page i.e. so that it appears as the total number of 'Assurance Type: Certification'?

**Comment by JbPasquier** [comment]
Current behaviour: I do compile the list from the ones that are shown then I check if there are any Certification, if so I add this filter. Then, I sort this list alphabetically.

If I do understand what you're asking me, you want this:

![image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/86c0576e-85f7-4021-a2e2-c24ad6471551)

To become:
- Ecological - Carbon
- Ecological - Soil health
- Ecological - Water
- Certification

Am I right? I can do this.

I can't arbitrary put Certification in the middle of Supporting Evidence Classification's tags without edge cases. Like say:
- Ecological - Carbon
- Ecological - Soil health
- Ecological - Water
- Certification
- Participation

Or I'll need some weird rules like "Put Certification right after the E". If it fits all of your use cases, I can do that too.

**Comment by kirstenalarsen** [comment]
It is fine for Certifications to be at the top
The key thing here is that Certifications in the Summary should ONLY be reading from Assurance Type: Certification, there shouldn't be any data on the Supporting Evidence label Certification

So like on the Rosnay profile, see the Supporting Evidence which correctly includes their Biodynamic Certification

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/4c9067fc-caca-4f31-95e0-a3dd7194d4f1)

BUT the summary currently doesn't 

Also, please can the Summary be same order ie. Ecological ad the top, Other at the bottom

**Comment by kirstenalarsen** [comment]
Certification at the top is fine

**Comment by kirstenalarsen** [comment]
Rosnay currently not showing the Certification in the Summary

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/d58e1c39-9dc6-4511-902a-2b4807cc41e7)

**Comment by JbPasquier** [comment]
> Also, please can the Summary be same order ie. Ecological ad the top, Other at the bottom

Please see the second part of this comment https://github.com/openfoodfoundation/sib-discovery-components/issues/8#issuecomment-2012136198

Should I force some custom sorting? It'll deeply bind the code with your datas. And so make this component only work for your datas from your API. Should I?

---

> BUT the summary currently doesn't

Exact, the summary is only based on the supporting evidence source. The kind of mix-mashing we're doing on the bottom one really needs to be avoided, we're parking bikes and elephants on the same place.

From the API perspective there are no relation in any manner between a Certification and a Supporting Evidence object.

I'll see if I can reach something there.

**Comment by kirstenalarsen** [comment]
hmmm, it's the mismash I want :) 
Understand if it can't happen
If it can happen then alphabetical is fine, just with Other at the bottom?

**Comment by JbPasquier** [comment]
Done.

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/dc91844b-8299-456e-9fd1-90ad68ccf42f)

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/b2d92e7c-34ee-4648-970f-fa9c123196cd)

**Comment by mariocarabotta** [comment]
this is looking great from my side.

leaving it to @kirstenalarsen for further testing

nice work!

**Comment by kirstenalarsen** [comment]
Yep looks good :)
