### ISSUE TITLE
Mobile width/logos

### ISSUE THREAD

**Issue by RebeccaOFN** [openfoodfoundation/sib-discovery-components#80]
We are seeing an issue where the logos in mobile view overlap the text (see image 1). I see there was some discussion of this issue before. #47 and gather it still needs to be fixed for Discover Regen as well. Do you have any timeline on this? @mariocarabotta , can you explain the temporary fix you put in place?  I also noticed that the top filters (Eat, Grow, Give) does not fit on a single line, at least on my tiny iphone 12 mini. Can we fix this? @JbPasquier 

![image1](https://github.com/user-attachments/assets/85201e7e-f611-476c-a376-f8ef12a7c891)
![image2](https://github.com/user-attachments/assets/75173f3c-44f7-456f-b78e-3b51d9b08312)

**Comment by JbPasquier** [comment]
I made some fixes for 375px wide resolution in the 2.1.0-waterloo.4 version. It should be live soon, time for it to propagate through the CDN.

![Screen Shot 2024-09-04 at 09 34 17](https://github.com/user-attachments/assets/7a078662-72ca-4aec-9714-bd4c456bacd7)

**Comment by RebeccaOFN** [comment]
Looks good, thank you! I'm closing this issue.
