### ISSUE TITLE
Final modifications to component design

### ISSUE THREAD

**Issue by RebeccaOFN** [openfoodfoundation/sib-discovery-components#81]
@Louiscsn , these are the final small modifications we're requesting to the components. 

Directory page:
- Add 'See all' button, make buttons more square, and make selected button dark green / unselected buttons light green (see image)
- If possible, change category drop down so that it shows Category as a title but once expanded, shows 'All categories' as the first option

![Screenshot 2024-09-10 125609](https://github.com/user-attachments/assets/a1b57f48-d59a-4bd1-9c13-3349b5d3d265)

Profile page:
- Change 'Producer website' to just 'Website'

Let me know if you need clarification on anything.

**Comment by Louiscsn** [comment]
@RebeccaOFN understood! regarding your second request:

> category drop down so that it shows Category as a title but once expanded, shows 'All categories' as the first option

It looks like the [staging ](https://waterlooregionfood.ca/staging/5285/directory/) is already compliant? Or did I miss something?

**Comment by JbPasquier** [comment]
Done for "See all", more square buttons and "Website" instead of "Producer website".

Should be live soon, time for CDN propagation.

**Comment by RebeccaOFN** [comment]
> @RebeccaOFN understood! regarding your second request:
> 
> > category drop down so that it shows Category as a title but once expanded, shows 'All categories' as the first option
> 
> It looks like the [staging ](https://waterlooregionfood.ca/staging/5285/directory/) is already compliant? Or did I miss something?

Currently Category is both the title of the search field and the first option for searching. We would ideally like Category to be the title before selection but All Categories appear in the dropdown, if this is possible.
![Screenshot 2024-09-16 131341](https://github.com/user-attachments/assets/c6c10743-c544-45fa-be78-874755eac433)

**Comment by RebeccaOFN** [comment]
@JbPasquier , I don't see the changes yet. Do I need to do something on our end to implement the update?

**Comment by JbPasquier** [comment]
Looks good to me.

May I ask you what version is shown [on third line there](https://cdn.jsdelivr.net/npm/@startinblox/component-ofn-rpp@waterloo). Latest is 2.1.0-waterloo.5.

![image](https://github.com/user-attachments/assets/dce931b0-58d9-4e9b-9b72-d741e9d671a1)


> Currently Category is both the title of the search field and the first option for searching. We would ideally like Category to be the title before selection but All Categories appear in the dropdown, if this is possible.

As this one is driven by datas, without a more complex filtering implementation, I'll have to stick to one value. I can change it to "All Categories" but it'll be shown at both occurences.

**Comment by RebeccaOFN** [comment]
@JbPasquier the changes are showing up now. Looks good!

**Comment by RebeccaOFN** [comment]
@JbPasquier , I just touched base with David and we are going to leave the Category drop down as is, so the no further changes should be needed. I'm closing this issue. Thanks!
