### ISSUE TITLE
Rewrite producer URLs for component display

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/sib-discovery-components#82]
We installed the URL rewrite rules in the .htaccess file and the Wordpress theme functions.php. But it doesn't seem to work for producer pages.

On closer inspection, any URL containing `directory` is correctly routed to the directory page with the component except when there's an encoded slash `%2F` in the URL. So this URL doesn't work:

https://waterlooregionfood.ca/directory/waterloo-producer-details/@https%3A%2F%2Fapi.waterlooregionfood.ca%2Fwebhook%2Fregen_CAN%2Fproducer%3Fid%3DrecEHrrhv40giZQsE@

But this URL works:

https://waterlooregionfood.ca/directory/waterloo-producer-details/@https://api.waterlooregionfood.ca/webhook/regen_CAN/producer%3Fid=recPL9wPjlIXoBHUe@/

The URL with real slashes didn't work in the Australian setup because the webserver would replace double slashes with a single slash (`//` -> `/`). This doesn't seem to be a problem on the Canadian server.

So the only workaround I can think of is to change all links within the component to not encode slashes.

@JbPasquier, what do you think? Or do you have an idea which part of the hosting setup or Wordpress may be breaking this?

**Comment by JbPasquier** [comment]
Could it be that `AllowEncodedSlashes NoDecode` is not set in the hosting setup?

**Comment by mkllnk** [comment]
That's a great hint! Thank you.

@RebeccaOFN, can you reach out to the Bluehost support to get that configuration set? I don't think that we can do that in the htaccess file. It needs to be in the Apache VirtualHost configuration.

**Comment by RebeccaOFN** [comment]
Thanks @JbPasquier and @mkllnk . I won't be able to get to to this until Monday but I'll update you then.

**Comment by RebeccaOFN** [comment]
@JbPasquier , I've been in contact with our hosting provider and they only offer this configuration for dedicated server hosting, which would be a prohibitively expensive ongoing cost for this project. Is there an alternative solution?

**Comment by JbPasquier** [comment]
Not that I am aware of, we do need to have two URLs within one, one should be encoded.

**Comment by mkllnk** [comment]
@JbPasquier, do you think it's feasible to implement this workaround for now?

> change all links within the component to not encode slashes.

The project is launching and the only other option we have is to move the Wordpress site to another host that allows encoding slashes.

**Comment by JbPasquier** [comment]
Our framework does not support this option, we do need two urls within one and slash behaviour is rather erratic when it come to browsers.

**Comment by David-OFN-CA** [comment]
okay thanks for the update @JbPasquier - I'll close this issue for now, with a note that is an issue we will likely need to return to at some point if we intend to develop this project into something more like a commercial product, as the ability to directly link to producer profiles seems like pretty fundamental functionality for a site like this, and the cost of dedicated server hosting is prohibitive

**Comment by mkllnk** [comment]
@David-OFN-CA, the easiest solution is to move the Wordpress site to a different web host that doesn't use the Apache default configuration of disallowing encoded slashes.
