### ISSUE TITLE
Producer Profile: View producer website url and social links

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/sib-discovery-components#9]
I think the instagram link is not populating prefix correctly so leads to deadlink .. 

When I click on the instagram logo it's going to https://murrnongfarm/

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/cbedf478-cb4a-4b5a-8b79-fbdb75dc1528)

We have the full link in airtable, I'm not sure if the problem is in n8n or component? I'm giving to you first @JbPasquier but if the problem is in api please pass back to @mkllnk 

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/129824a6-cbbc-4bcb-83cd-59fc15b85b1d)

Facebook and LinkedIn seem good to go

**Comment by JbPasquier** [comment]
The issue is on your datas, I guess.

@mkllnk The `"dfc-b:URL": "murrnongfarm"` come from here: https://api.regenerative.org.au/webhook/b9c3687f-9f0f-4628-9bcc-f3331afb6fa8/enterprises/24/social_medias/instagram?id=recW1epOZsVUhJvRI

About the `https://`, I've handled it on client side, when it's missing I do add it.

**Comment by kirstenalarsen** [comment]
I think this means you to fix please @mkllnk

**Comment by kirstenalarsen** [comment]
still not working today


![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/13b6e21f-0d12-4bd0-9364-d85e081e07c7)

**Comment by mkllnk** [comment]
I'm hoping to fix this in the DFC API with the next release:

* https://github.com/openfoodfoundation/openfoodnetwork/pull/12299

**Comment by kirstenalarsen** [comment]
yep seems good I think :)
